CREATE DATABASE customer_shopping_behavior;

SELECT * FROM customer_shopping_behavior.customer LIMIT 20;

# 1. What is the total revenue generated by male vs female customers?

SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

# 2. Which customer used a discount but still spent more thn the avg purchase amt?

SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = "YES" AND purchase_amount >=(SELECT AVG(purchase_amount)FROM customer);


# 3. Which r thr top 5 products with the highest average review rating?

SELECT item_purchased,ROUND(AVG(review_rating),2) as "Average Product Rating"
FROM customer 
GROUP BY item_purchased
ORDER BY AVG(review_rating) desc
LIMIT 5;

# 4. Compare the avg purchase amt btw Standard and Express Shipping.

SELECT shipping_type,
ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type in ("Standard","Express")
GROUP BY shipping_type;

# 5. Do subscribbed customers spend more? Compare to avg spend and total revenue btw subscribers and non sub.. 

SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend desc;

# 6. Which 5 products have the highest percentage of purchase with discounts applied. 

SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied = "YES" THEN 1 ELSE 0 END)/COUNT(*) * 100,2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_applied desc
LIMIT 5;

# 7. Segment customers into New , Returning and Loyal based on their total no. of previous purchases,n show the count of each segment. 

with customer_type as (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'NEW'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)
SELECT customer_segment ,COUNT(*) as "Number of customers"
FROM customer_type
GROUP BY customer_segment;


# 8. What r the top 3 most purchased products within each category. 

with item_counts as (
SELECT category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER (partition by category ORDER BY COUNT(customer_id)desc) as item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT item_rank,category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <= 3;


# 9. Are customers who are repeat buyers (more thn 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

# 10. What is the revenue contribution of each age group?

SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;





